version: '3.5'

services:
  web:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    expose:
      - '80'
    environment:
       VIRTUAL_HOST: homeswithaudrey.local,www.homeswithaudrey.local
       VIRTUAL_PORT: 80

  api:
    build:
      context: ./flask
      dockerfile: Dockerfile.prod
    expose:
      - '80'
    restart: unless-stopped
    env_file:
      - flask/.prod.env
    environment:
       VIRTUAL_HOST: api.homeswithaudrey.local,www.api.homeswithaudrey.local
       VIRTUAL_PORT: 80


networks:
    default:
       external:
         name: nginx-proxy