version: '3.5'

services:
  web:
    build:
      context: ./react
      dockerfile: Dockerfile
    expose:
      - '8080'
    volumes:
      - ~/Projects/mom_website/react:/app
    environment:
       VIRTUAL_HOST: homeswithaudrey.local,www.homeswithaudrey.local
       VIRTUAL_PORT: 8080

  api:
    build:
      context: ./flask
      dockerfile: Dockerfile
    expose:
      - '80'
    volumes:
      - ~/Projects/mom_website/flask:/home/api
    env_file:
      - flask/.dev.env
    environment:
       VIRTUAL_HOST: api.homeswithaudrey.local,www.api.homeswithaudrey.local
       VIRTUAL_PORT: 80


networks:
    default:
       external:
         name: nginx-proxy