version: '3.5'

services:
  web:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: homeswithaudrey.com,www.homeswithaudrey.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: homeswithaudrey.com, www.homeswithaudrey.com
      LETSENCRYPT_EMAIL: thenickjames@gmail.com

  api:
    build:
      context: ./flask
      dockerfile: Dockerfile.prod
    expose:
      - '80'
    restart: unless-stopped
    env_file:
      - flask/.prod.env
    environment:
      VIRTUAL_HOST: api.homeswithaudrey.com,www.api.homeswithaudrey.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: homeswithaudrey.com, www.homeswithaudrey.com
      LETSENCRYPT_EMAIL: thenickjames@gmail.com


networks:
    default:
       external:
         name: nginx-proxy