version: '3.5'

services:
  web:
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
  api:
    build:
      context: ./flask
      dockerfile: Dockerfile.prod
    ports:
      - '5000:5000'
    env_file:
      - flask/.prod.env
