# Stage 0, "build-stage"
FROM node:8-alpine as build-stage
RUN mkdir /app
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ .
RUN npm run build

# Stage 1, serve built code
FROM nginx:1.15-alpine
COPY --from=build-stage /app/dist/ /usr/share/nginx/html
COPY --from=build-stage /app/assets/images/OpenGraph.png /usr/share/nginx/html/static
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
