FROM python:3.6-alpine

RUN adduser -D api

WORKDIR /home/api

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

USER api
COPY . .

CMD gunicorn -b :5000 --access-logfile - --error-logfile - src:app